import asyncio
import os
import re
from typing import Union
import yt_dlp
from pyrogram.enums import MessageEntityType
from pyrogram.types import Message
from py_yt import VideosSearch
from ShrutixMusic.utils.formatters import time_to_seconds
import aiohttp
from ShrutixMusic import LOGGER

# --- INFLUX API CONFIGURATION ---
# Step 1: Get your API key from @InflexAPIBot on Telegram
# Step 2: Replace API_KEY below with your key
API_URL = "https://teaminflex.xyz"
# USER-PROVIDED API KEY:
API_KEY = "INFLEX66417728D" # <-- Your key has been inserted here
# --- END CONFIGURATION ---

# --- Logger Setup ---
logger = LOGGER(__name__)

# --- UTILITY FUNCTIONS ---

async def shell_cmd(cmd):
    """Executes a shell command and returns output."""
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    out, errorz = await proc.communicate()
    if errorz:
        if "unavailable videos are hidden" in (errorz.decode("utf-8")).lower():
            return out.decode("utf-8")
        else:
            return errorz.decode("utf-8")
    return out.decode("utf-8")


async def _download_yt_dlp(link: str, download_type: str) -> Union[str, None]:
    """
    Final failsafe download using yt-dlp for audio or video.
    This function uses shell_cmd for simplicity.
    """
    video_id = link.split('v=')[-1].split('&')[0] if 'v=' in link else link
    DOWNLOAD_DIR = "downloads"
    os.makedirs(DOWNLOAD_DIR, exist_ok=True)
    
    # Determine command and final extension based on type
    if download_type == "audio":
        ext = "webm"
        # Command for best audio quality, converting to webm for PyTgCalls compatibility
        cmd_options = f"-f bestaudio --extract-audio --audio-format {ext} --audio-quality 0"
    elif download_type == "video":
        ext = "mp4"
        # Command for best video up to 720p + best audio, merged into mp4
        cmd_options = f"-f '(bestvideo[height<=?720][ext=mp4]/bestvideo[height<=?720]) + bestaudio' --merge-output-format mp4"
    else:
        logger.error(f"Invalid download type: {download_type}")
        return None

    # Output template: downloads/{video_id}.%(ext)s - yt-dlp handles the exact extension
    output_template = os.path.join(DOWNLOAD_DIR, f"{video_id}.%(ext)s")
    
    # Full yt-dlp command
    cmd = (
        f"yt-dlp -o '{output_template}' "
        f"{cmd_options} "
        f"--no-playlist "
        f"--geo-bypass "
        f"'{link}'"
    )
    
    logger.info(f"[{download_type.upper()}] Attempting yt-dlp fallback download...")
    
    # Execute the command
    await shell_cmd(cmd) 
    
    # After download, check for all common file paths generated by yt-dlp
    potential_files = [
        os.path.join(DOWNLOAD_DIR, f"{video_id}.{ext}"), # Targeted path (mp4 or webm)
        os.path.join(DOWNLOAD_DIR, f"{video_id}.mkv"), # Common video merge output
        os.path.join(DOWNLOAD_DIR, f"{video_id}.mp4"), # Another possibility
        os.path.join(DOWNLOAD_DIR, f"{video_id}.opus"), # Another audio format
        os.path.join(DOWNLOAD_DIR, f"{video_id}.m4a"), # Another audio format
        os.path.join(DOWNLOAD_DIR, f"{video_id}.webm"), # Another audio format
    ]
    
    for final_file in potential_files:
        if os.path.exists(final_file):
            logger.info(f"[{download_type.upper()}] Downloaded successfully via yt-dlp fallback: {final_file}")
            return final_file
    
    logger.error(f"[{download_type.upper()}] yt-dlp fallback failed for {link}.")
    return None


# ==============================================
# 🎵 AUDIO DOWNLOAD (Inflex API + yt-dlp Fallback)
# ==============================================
async def download_song(link: str) -> Union[str, None]:
    video_id = link.split('v=')[-1].split('&')[0] if 'v=' in link else link
    logger.info(f"🎵 [AUDIO] Starting download process for ID: {video_id}")

    if not video_id or len(video_id) < 3:
        # Re-check for existing local file before attempting API, but only for webm
        file_path = os.path.join("downloads", f"{video_id}.webm")
        if os.path.exists(file_path):
            logger.info(f"🎵 [LOCAL] Found existing file for ID: {video_id}")
            return file_path
        return

    DOWNLOAD_DIR = "downloads"
    os.makedirs(DOWNLOAD_DIR, exist_ok=True)
    file_path = os.path.join(DOWNLOAD_DIR, f"{video_id}.webm")
    
    # Check 1: Local file exists
    if os.path.exists(file_path):
        logger.info(f"🎵 [LOCAL] Found existing file for ID: {video_id}")
        return file_path

    # Check 2: Primary API (Inflex)
    try:
        async with aiohttp.ClientSession() as session:
            payload = {"url": video_id, "type": "audio"}
            headers = {
                "Content-Type": "application/json",
                "X-API-KEY": API_KEY
            }

            # 🔹 Step 1: Trigger API and wait until it's ready
            async with session.post(f"{API_URL}/download", json=payload, headers=headers) as response:
                data = await response.json(content_type=None)

                if response.status != 200 or data.get("status") == "error":
                    detail = data.get("detail", f"HTTP {response.status}")
                    logger.error(f"[AUDIO] Inflex API Failed: {detail}. Falling back...")
                    raise Exception(f"Inflex API failed: {detail}")

                download_link = f"{API_URL}{data['download_url']}"
                logger.info(f"🎵 [API] Download link obtained.")

            # 🔹 Step 2: Download the ready file
            async with session.get(download_link) as file_response:
                if file_response.status != 200:
                    logger.error(f"[AUDIO] Download failed ({file_response.status}). Falling back...")
                    raise Exception(f"Inflex Download failed with status {file_response.status}")
                    
                with open(file_path, "wb") as f:
                    async for chunk in file_response.content.iter_chunked(8192):
                        f.write(chunk)

        logger.info(f"🎵 [API] Download completed successfully for ID: {video_id}")
        return file_path

    except Exception as e:
        logger.warning(f"[AUDIO] Inflex API failed. Trying yt-dlp fallback.")
        pass # Continue to fallback

    # Check 3: Fallback (yt-dlp)
    downloaded_file = await _download_yt_dlp(link, "audio")
    
    if downloaded_file:
        return downloaded_file
        
    logger.error("All audio download methods failed.")
    return None


# ==============================================
# 🎥 VIDEO DOWNLOAD (Inflex API + yt-dlp Fallback)
# ==============================================
async def download_video(link: str) -> Union[str, None]:
    video_id = link.split('v=')[-1].split('&')[0] if 'v=' in link else link
    logger.info(f"🎥 [VIDEO] Starting download process for ID: {video_id}")

    if not video_id or len(video_id) < 3:
        return

    DOWNLOAD_DIR = "downloads"
    os.makedirs(DOWNLOAD_DIR, exist_ok=True)
    
    # Check for existing video file path (mp4 or mkv)
    for ext in ['mp4', 'mkv']:
        file_path = os.path.join(DOWNLOAD_DIR, f"{video_id}.{ext}")
        if os.path.exists(file_path):
            logger.info(f"🎥 [LOCAL] Found existing file for ID: {video_id}")
            return file_path

    # Check 2: Primary API (Inflex)
    final_file_path = os.path.join(DOWNLOAD_DIR, f"{video_id}.mp4") # Default path assumption
    try:
        async with aiohttp.ClientSession() as session:
            payload = {"url": video_id, "type": "video"}
            headers = {
                "Content-Type": "application/json",
                "X-API-KEY": API_KEY
            }

            # 🔹 Step 1: Trigger API and wait internally
            async with session.post(f"{API_URL}/download", json=payload, headers=headers) as response:
                data = await response.json(content_type=None)

                if response.status != 200 or data.get("status") == "error":
                    detail = data.get("detail", f"HTTP {response.status}")
                    logger.error(f"[VIDEO] Inflex API Failed: {detail}. Falling back...")
                    raise Exception(f"Inflex API failed: {detail}")

                download_link = f"{API_URL}{data['download_url']}"
                logger.info(f"🎥 [API] Download link obtained.")

            # 🔹 Step 2: Download the ready file
            async with session.get(download_link) as file_response:
                if file_response.status != 200:
                    logger.error(f"[VIDEO] Download failed ({file_response.status}). Falling back...")
                    raise Exception(f"Inflex Download failed with status {file_response.status}")
                
                # Determine final file path
                content_disposition = file_response.headers.get('Content-Disposition', '')
                ext_match = re.search(r'filename\*?=[^;]+\.(\w+)', content_disposition)
                extension = ext_match.group(1).lower() if ext_match else 'mp4'
                final_file_path = os.path.join(DOWNLOAD_DIR, f"{video_id}.{extension}")

                with open(final_file_path, "wb") as f:
                    async for chunk in file_response.content.iter_chunked(8192):
                        f.write(chunk)

        logger.info(f"🎥 [API] Download completed successfully for ID: {video_id}")
        return final_file_path

    except Exception as e:
        logger.warning(f"[VIDEO] Inflex API failed. Trying yt-dlp fallback.")
        pass # Continue to fallback

    # Check 3: Fallback (yt-dlp)
    downloaded_file = await _download_yt_dlp(link, "video")
    
    if downloaded_file:
        return downloaded_file
        
    logger.error("All video download methods failed.")
    return None

# --- YOUTUBE API CLASS (No changes needed here, as it calls the main functions) ---

class YouTubeAPI:
    def __init__(self):
        self.base = "https://www.youtube.com/watch?v="
        self.regex = r"(?:youtube\.com|youtu\.be)"
        self.status = "https://www.youtube.com/oembed?url="
        self.listbase = "https://youtube.com/playlist?list="
        self.reg = re.compile(r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])")

    async def exists(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        return bool(re.search(self.regex, link))

    async def url(self, message_1: Message) -> Union[str, None]:
        messages = [message_1]
        if message_1.reply_to_message:
            messages.append(message_1.reply_to_message)
        for message in messages:
            if message.entities:
                for entity in message.entities:
                    if entity.type == MessageEntityType.URL:
                        text = message.text or message.caption
                        return text[entity.offset: entity.offset + entity.length]
            elif message.caption_entities:
                for entity in message.caption_entities:
                    if entity.type == MessageEntityType.TEXT_LINK:
                        return entity.url
        return None

    async def details(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
            duration_min = result["duration"]
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
            vidid = result["id"]
            duration_sec = int(time_to_seconds(duration_min)) if duration_min else 0
        return title, duration_min, duration_sec, thumbnail, vidid

    async def title(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            return result["title"]

    async def duration(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            return result["duration"]

    async def thumbnail(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            return result["thumbnails"][0]["url"].split("?")[0]

    async def video(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        
        # Now calls the robust download_video function
        downloaded_file = await download_video(link)
        if downloaded_file:
            # Return 1 for success status, and the file path
            return 1, downloaded_file
        else:
            # Return 0 for failure, and an error message
            return 0, "Video download failed via all methods (Inflex API and yt-dlp fallback)."

    async def playlist(self, link, limit, user_id, videoid: Union[bool, str] = None):
        if videoid:
            link = self.listbase + link
        if "&" in link:
            link = link.split("&")[0]
        playlist = await shell_cmd(
            f"yt-dlp -i --get-id --flat-playlist --playlist-end {limit} --skip-download {link}"
        )
        try:
            result = [key for key in playlist.split("\n") if key]
        except:
            result = []
        return result

    async def track(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
            duration_min = result["duration"]
            vidid = result["id"]
            yturl = result["link"]
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
        track_details = {
            "title": title,
            "link": yturl,
            "vidid": vidid,
            "duration_min": duration_min,
            "thumb": thumbnail,
        }
        return track_details, vidid

    async def formats(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        ytdl_opts = {"quiet": True}
        ydl = yt_dlp.YoutubeDL(ytdl_opts)
        with ydl:
            formats_available = []
            r = ydl.extract_info(link, download=False)
            for format in r["formats"]:
                try:
                    if "dash" not in str(format["format"]).lower():
                        formats_available.append(
                            {
                                "format": format["format"],
                                "filesize": format.get("filesize"),
                                "format_id": format["format_id"],
                                "ext": format["ext"],
                                "format_note": format["format_note"],
                                "yturl": link,
                            }
                        )
                except:
                    continue
        return formats_available, link

    async def slider(self, link: str, query_type: int, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        a = VideosSearch(link, limit=10)
        result = (await a.next()).get("result")
        title = result[query_type]["title"]
        duration_min = result[query_type]["duration"]
        vidid = result[query_type]["id"]
        thumbnail = result[query_type]["thumbnails"][0]["url"].split("?")[0]
        return title, duration_min, thumbnail, vidid

    async def download(
        self,
        link: str,
        mystic,
        video: Union[bool, str] = None,
        videoid: Union[bool, str] = None,
        songaudio: Union[bool, str] = None,
        songvideo: Union[bool, str] = None,
        format_id: Union[bool, str] = None,
        title: Union[bool, str] = None,
    ) -> tuple[Union[str, None], bool]:
        if videoid:
            link = self.base + link

        downloaded_file = None
        
        # Check if video or audio download is requested
        if video or songvideo:
            # Use the robust video download function
            downloaded_file = await download_video(link)
        else: # Covers songaudio and default audio case
            # Use the robust audio download function
            downloaded_file = await download_song(link)
        
        # Return the file path and True (for success) or False (for failure)
        if downloaded_file:
            return downloaded_file, True 
        else:
            return None, False
            
